
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8




#Spring Security config
#springsecurityconfig:
#  logoutsuccessurl: /
#  permitall: /api
#  deniedpage: deny
#  urlroles: /**/ = admin;
#            /**/user = admin,user


